name: 1Password
on: push
env:
  OP_DEVICE: ${{ github.run_id }}
jobs:
  sync-secrets:
    name: Sync Secrets
    runs-on: ubuntu-20.04
    steps:
      - name: Setup 1Password
        uses: defendabot/github-action-1password@main
        with:
          email: ${{ secrets.email }}
          password: ${{ secrets.password }}
          secret: ${{ secrets.secret }}
      - name: List vaults
        run: op list vaults
