name: 1Password
on: push
jobs:
  sync-secrets:
    name: Sync Secrets
    runs-on: ubuntu-20.04
    steps:
      - name: Setup 1Password
        uses: defendabot/github-action-1password@main
        with:
          email: ${{ secrets.email }}
          password: ${{ secrets.password }}
          secret: ${{ secrets.secret }}
      - name: Sign in with 1Password
        id: signin
        run: echo "${{ secrets.password }}" | op signin my ${{ secrets.email }} ${{ secrets.secret }} --raw
      - name: Save session
        run: echo "::set-env name=OP_SESSION_my::$(echo "${{ secrets.password }}" | op signin my ${{ secrets.email }} ${{ secrets.secret }} --raw)"
      - name: List vaults
        run: op list vaults
