name: 1Password
on: push
jobs:
  sync-secrets:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup 1Password
        uses: defendabot/github-action-1password@main
        with:
          email: ${{ secrets.email }}
          password: ${{ secrets.password }}
          secret: ${{ secrets.secret }}
